sudo: false
language: node_js
services:
- mysql
- mongodb
- redis-server
- postgresql
before_install:
- 'if [ "${TRAVIS_NODE_VERSION}" == "8" ]; then npm install -g npm@4; fi'
node_js:
- '8'
- '7'
- 7.9.0
- '6'
- '5'
- '4'
- '0.12'
- '0.10'
env:
- TAV=generic-pool,mysql,redis,koa-router
- TAV=ioredis,pg
- TAV=bluebird
- TAV=knex,ws,graphql,express-graphql
matrix:
  fast_finish: true
  allow_failures:
  - node_js: '7'
notifications:
  slack:
    rooms:
      secure: PR+vjohDfGmidHhaIboj896iad3OIa4pked1Mib+XB5FF3tWfpDjBBNmEBizRbpwzxy4oHgOr22LBNvi+zkE674wXY3VUM+Wx9pJztlqotcON/hBjcJd993MfixRHN0RShxn4omaLfiqrZ+8iUFD5MQKdLKqBG/IG2toxdhuDkU=
    on_success: change
    on_failure: change
    on_pull_requests: false
